export const DAYS_OF_WEEK = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export const INDIVIDUAL_MUSCLE_GROUPS = [
  "Rest",
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Forearms",
  "Legs",
  "Abs",
  "Cardio"
];

export const EXERCISE_DATABASE = [
  { "id": 1, "name": "Barbell Bench Press", "muscleGroup": "Chest" },
  { "id": 2, "name": "Incline Dumbbell Press", "muscleGroup": "Chest" },
  { "id": 3, "name": "Cable Flyes", "muscleGroup": "Chest" },
  { "id": 81, "name": "Dumbbell Press", "muscleGroup": "Chest" },
  { "id": 82, "name": "Push-Ups", "muscleGroup": "Chest" },
  { "id": 83, "name": "Machine Chest Press", "muscleGroup": "Chest" },
  { "id": 84, "name": "Dumbbell Flyes", "muscleGroup": "Chest" },
  { "id": 85, "name": "Cable Crossovers", "muscleGroup": "Chest" },
  { "id": 86, "name": "Pec Deck Machine", "muscleGroup": "Chest" },
  { "id": 87, "name": "Floor Press", "muscleGroup": "Chest" },
  { "id": 150, "name": "Decline Bench Press", "muscleGroup": "Chest" },
  { "id": 151, "name": "Diamond Push-Ups", "muscleGroup": "Chest" },
  { "id": 152, "name": "Chest Dips", "muscleGroup": "Chest" },
  { "id": 153, "name": "Landmine Press", "muscleGroup": "Chest" },
  { "id": 9, "name": "Pull-ups", "muscleGroup": "Back" },
  { "id": 11, "name": "Seated Cable Rows", "muscleGroup": "Back" },
  { "id": 88, "name": "Lat Pulldowns", "muscleGroup": "Back" },
  { "id": 89, "name": "Bent-Over Barbell Rows", "muscleGroup": "Back" },
  { "id": 90, "name": "Single-Arm Dumbbell Rows", "muscleGroup": "Back" },
  { "id": 91, "name": "T-Bar Rows", "muscleGroup": "Back" },
  { "id": 92, "name": "Face Pulls", "muscleGroup": "Back" },
  { "id": 93, "name": "Straight-Arm Pulldowns", "muscleGroup": "Back" },
  { "id": 100, "name": "Barbell Shrugs", "muscleGroup": "Back" },
  { "id": 101, "name": "Dumbbell Shrugs", "muscleGroup": "Back" },
  { "id": 102, "name": "Farmer's Walk", "muscleGroup": "Back" },
  { "id": 103, "name": "Rack Pulls", "muscleGroup": "Back" },
  { "id": 104, "name": "Cable Shrugs", "muscleGroup": "Back" },
  { "id": 105, "name": "Trap Bar Shrugs", "muscleGroup": "Back" },
  { "id": 154, "name": "Chin-ups", "muscleGroup": "Back" },
  { "id": 155, "name": "Pendlay Rows", "muscleGroup": "Back" },
  { "id": 156, "name": "Inverted Rows", "muscleGroup": "Back" },
  { "id": 157, "name": "Meadows Rows", "muscleGroup": "Back" },
  { "id": 17, "name": "Military Press", "muscleGroup": "Shoulders" },
  { "id": 19, "name": "Lateral Raises", "muscleGroup": "Shoulders" },
  { "id": 94, "name": "Overhead Press", "muscleGroup": "Shoulders" },
  { "id": 95, "name": "Arnold Press", "muscleGroup": "Shoulders" },
  { "id": 96, "name": "Front Raises", "muscleGroup": "Shoulders" },
  { "id": 97, "name": "Upright Rows", "muscleGroup": "Shoulders" },
  { "id": 98, "name": "Reverse Pec Deck Flyes", "muscleGroup": "Shoulders" },
  { "id": 99, "name": "Push Press", "muscleGroup": "Shoulders" },
  { "id": 158, "name": "Bradford Press", "muscleGroup": "Shoulders" },
  { "id": 159, "name": "Cable Lateral Raises", "muscleGroup": "Shoulders" },
  { "id": 160, "name": "Rear Delt Rows", "muscleGroup": "Shoulders" },
  { "id": 161, "name": "Handstand Push-Ups", "muscleGroup": "Shoulders" },
  { "id": 38, "name": "Barbell Curls", "muscleGroup": "Biceps" },
  { "id": 40, "name": "Hammer Curls", "muscleGroup": "Biceps" },
  { "id": 113, "name": "Dumbbell Curls", "muscleGroup": "Biceps" },
  { "id": 114, "name": "Preacher Curls", "muscleGroup": "Biceps" },
  { "id": 115, "name": "EZ-Bar Curls", "muscleGroup": "Biceps" },
  { "id": 116, "name": "Concentration Curls", "muscleGroup": "Biceps" },
  { "id": 117, "name": "Incline Dumbbell Curls", "muscleGroup": "Biceps" },
  { "id": 118, "name": "Cable Curls", "muscleGroup": "Biceps" },
  { "id": 162, "name": "Spider Curls", "muscleGroup": "Biceps" },
  { "id": 163, "name": "21s", "muscleGroup": "Biceps" },
  { "id": 164, "name": "Drag Curls", "muscleGroup": "Biceps" },
  { "id": 165, "name": "Cable Hammer Curls", "muscleGroup": "Biceps" },
  { "id": 33, "name": "Skull Crushers", "muscleGroup": "Triceps" },
  { "id": 30, "name": "Rope Pushdowns", "muscleGroup": "Triceps" },
  { "id": 106, "name": "Triceps Pushdowns", "muscleGroup": "Triceps" },
  { "id": 107, "name": "Close-Grip Bench Press", "muscleGroup": "Triceps" },
  { "id": 108, "name": "Overhead Dumbbell Extension", "muscleGroup": "Triceps" },
  { "id": 109, "name": "Skullcrushers", "muscleGroup": "Triceps" },
  { "id": 110, "name": "Dips", "muscleGroup": "Triceps" },
  { "id": 111, "name": "Bench Dips", "muscleGroup": "Triceps" },
  { "id": 112, "name": "Tate Press", "muscleGroup": "Triceps" },
  { "id": 166, "name": "JM Press", "muscleGroup": "Triceps" },
  { "id": 167, "name": "Cable Overhead Extension", "muscleGroup": "Triceps" },
  { "id": 168, "name": "Single-Arm Cable Pushdowns", "muscleGroup": "Triceps" },
  { "id": 119, "name": "Wrist Curls", "muscleGroup": "Forearms" },
  { "id": 120, "name": "Reverse Wrist Curls", "muscleGroup": "Forearms" },
  { "id": 121, "name": "Plate Pinches", "muscleGroup": "Forearms" },
  { "id": 122, "name": "Towel Pull-Ups", "muscleGroup": "Forearms" },
  { "id": 123, "name": "Reverse Barbell Curls", "muscleGroup": "Forearms" },
  { "id": 124, "name": "Wrist Roller", "muscleGroup": "Forearms" },
  { "id": 169, "name": "Dead Hangs", "muscleGroup": "Forearms" },
  { "id": 170, "name": "Farmer's Carry", "muscleGroup": "Forearms" },
  { "id": 171, "name": "Gripper Training", "muscleGroup": "Forearms" },
  { "id": 172, "name": "Finger Curls", "muscleGroup": "Forearms" },
  { "id": 60, "name": "Barbell Squats", "muscleGroup": "Legs" },
  { "id": 61, "name": "Leg Press", "muscleGroup": "Legs" },
  { "id": 66, "name": "Romanian Deadlifts", "muscleGroup": "Legs" },
  { "id": 80, "name": "Single-Leg Calf Raises", "muscleGroup": "Legs" },
  { "id": 125, "name": "Barbell Hip Thrusts", "muscleGroup": "Legs" },
  { "id": 126, "name": "Glute Bridges", "muscleGroup": "Legs" },
  { "id": 127, "name": "Squats (Wide Stance)", "muscleGroup": "Legs" },
  { "id": 128, "name": "Lunges", "muscleGroup": "Legs" },
  { "id": 129, "name": "Step-Ups", "muscleGroup": "Legs" },
  { "id": 130, "name": "Cable Kickbacks", "muscleGroup": "Legs" },
  { "id": 131, "name": "Bulgarian Split Squats", "muscleGroup": "Legs" },
  { "id": 132, "name": "Deadlifts", "muscleGroup": "Legs" },
  { "id": 133, "name": "Leg Extensions", "muscleGroup": "Legs" },
  { "id": 134, "name": "Front Squats", "muscleGroup": "Legs" },
  { "id": 135, "name": "Hack Squats", "muscleGroup": "Legs" },
  { "id": 136, "name": "Sissy Squats", "muscleGroup": "Legs" },
  { "id": 137, "name": "Lying Leg Curls", "muscleGroup": "Legs" },
  { "id": 138, "name": "Seated Leg Curls", "muscleGroup": "Legs" },
  { "id": 139, "name": "Good Mornings", "muscleGroup": "Legs" },
  { "id": 140, "name": "Glute-Ham Raises (GHR)", "muscleGroup": "Legs" },
  { "id": 141, "name": "Single-Leg Deadlifts", "muscleGroup": "Legs" },
  { "id": 142, "name": "Nordic Ham Curls", "muscleGroup": "Legs" },
  { "id": 143, "name": "Kettlebell Swings", "muscleGroup": "Legs" },
  { "id": 144, "name": "Standing Calf Raises", "muscleGroup": "Legs" },
  { "id": 145, "name": "Seated Calf Raises", "muscleGroup": "Legs" },
  { "id": 146, "name": "Donkey Calf Raises", "muscleGroup": "Legs" },
  { "id": 147, "name": "Calf Press on Leg Machine", "muscleGroup": "Legs" },
  { "id": 148, "name": "Jump Rope", "muscleGroup": "Legs" },
  { "id": 149, "name": "Box Jumps", "muscleGroup": "Legs" },
  { "id": 173, "name": "Goblet Squats", "muscleGroup": "Legs" },
  { "id": 174, "name": "Walking Lunges", "muscleGroup": "Legs" },
  { "id": 175, "name": "Pistol Squats", "muscleGroup": "Legs" },
  { "id": 176, "name": "Wall Sits", "muscleGroup": "Legs" },
  { "id": 57, "name": "Cable Crunches", "muscleGroup": "Abs" },
  { "id": 71, "name": "Hanging Leg Raises", "muscleGroup": "Abs" },
  { "id": 177, "name": "Plank", "muscleGroup": "Abs" },
  { "id": 178, "name": "Russian Twists", "muscleGroup": "Abs" },
  { "id": 179, "name": "Bicycle Crunches", "muscleGroup": "Abs" },
  { "id": 180, "name": "Mountain Climbers", "muscleGroup": "Abs" },
  { "id": 181, "name": "Ab Wheel Rollouts", "muscleGroup": "Abs" },
  { "id": 182, "name": "Side Plank", "muscleGroup": "Abs" },
  { "id": 183, "name": "Dead Bug", "muscleGroup": "Abs" },
  { "id": 184, "name": "Bird Dog", "muscleGroup": "Abs" },
  { "id": 185, "name": "Leg Raises", "muscleGroup": "Abs" },
  { "id": 186, "name": "V-Ups", "muscleGroup": "Abs" },
  { "id": 187, "name": "Pallof Press", "muscleGroup": "Abs" },
  { "id": 188, "name": "Hollow Body Hold", "muscleGroup": "Abs" },
  { "id": 189, "name": "Wood Choppers", "muscleGroup": "Abs" },
  { "id": 190, "name": "Flutter Kicks", "muscleGroup": "Abs" },
  { "id": 191, "name": "Scissor Kicks", "muscleGroup": "Abs" },
  { "id": 192, "name": "Toe Touches", "muscleGroup": "Abs" },
  { "id": 193, "name": "Treadmill Running", "muscleGroup": "Cardio" },
  { "id": 194, "name": "Stationary Bike", "muscleGroup": "Cardio" },
  { "id": 195, "name": "Rowing Machine", "muscleGroup": "Cardio" },
  { "id": 196, "name": "Elliptical", "muscleGroup": "Cardio" },
  { "id": 197, "name": "Stair Climber", "muscleGroup": "Cardio" },
  { "id": 198, "name": "Battle Ropes", "muscleGroup": "Cardio" },
  { "id": 199, "name": "Burpees", "muscleGroup": "Cardio" },
  { "id": 200, "name": "High Knees", "muscleGroup": "Cardio" },
  { "id": 201, "name": "Swimming", "muscleGroup": "Cardio" },
  { "id": 202, "name": "Cycling", "muscleGroup": "Cardio" },
  { "id": 203, "name": "Jumping Jacks", "muscleGroup": "Cardio" },
  { "id": 204, "name": "Sprint Intervals", "muscleGroup": "Cardio" },
  { "id": 205, "name": "Boxing", "muscleGroup": "Cardio" },
  { "id": 206, "name": "Assault Bike", "muscleGroup": "Cardio" },
  { "id": 207, "name": "Sled Push", "muscleGroup": "Cardio" },
  { "id": 208, "name": "Sled Pull", "muscleGroup": "Cardio" },
  { "id": 209, "name": "Ski Erg", "muscleGroup": "Cardio" },
  { "id": 210, "name": "Jump Rope HIIT", "muscleGroup": "Cardio" }
];